import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "@/src/app/globals.css";
import Header from "@/src/components/Header";
import { auth } from "@/auth";
import { getSession } from "@/src/utils/session";

const font = Jost({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Hotel Booking Application",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getSession();
  return (
    <html lang='en'>
      <body className={`${font.className}`}>
        <Header isLogin={!!user} />
        <div className='h-full'>{children}</div>
      </body>
    </html>
  );
}
