import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "@/src/app/globals.css";
import AdminHeader from "@/src/components/AdminHeader";

const font = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotel Booking Application Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <AdminHeader />
        {children}
      </body>
    </html>
  );
}
